# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------

title: "Yucheng Xing"
first_name: Yucheng
last_name: Xing
description: >
  Ph.D. Candidate in Electrical and Computer Engineering, Stony Brook University.
footer_text: >
  © 2025 Yucheng Xing. All rights reserved.
keywords: diffusion models, generative AI, spatio-temporal forecasting, graph learning
lang: en
icon: ⚛️

# 正确的网址设置
url: "https://sbu-ycx.github.io"
baseurl: ""       # 主页必须留空

back_to_top: true

# -----------------------------------------------------------------------------
# Theme & Layout
# -----------------------------------------------------------------------------

navbar_fixed: true
footer_fixed: true
search_enabled: true
socials_in_search: true
posts_in_search: true
bib_search: true
max_width: 930px

# -----------------------------------------------------------------------------
# Author & Social Links
# -----------------------------------------------------------------------------

author:
  name: "Yucheng Xing"
  role: "Ph.D. Candidate"
  affiliation: "Department of Electrical and Computer Engineering, Stony Brook University"
  email: "yucheng.xing@stonybrook.edu"
  website: "https://yuchengxing.me"
  github: "sbu-ycx"
  linkedin: ""        # 如果有可填
  scholar: ""         # Google Scholar ID

# -----------------------------------------------------------------------------
# Theme colors
# -----------------------------------------------------------------------------
repo_theme_light: default
repo_theme_dark: dark
theme_color: "#26734d"     # 主色调：深科研绿

# -----------------------------------------------------------------------------
# Blog / News (可忽略)
# -----------------------------------------------------------------------------
blog_name: "News"
blog_description: "Recent updates and publications"

pagination:
  enabled: true

# -----------------------------------------------------------------------------
# Analytics & SEO
# -----------------------------------------------------------------------------
enable_google_analytics: false
enable_darkmode: true
serve_og_meta: true
serve_schema_org: false

# -----------------------------------------------------------------------------
# Jekyll Scholar (用于 Publications)
# -----------------------------------------------------------------------------
scholar:
  last_name: [Xing]
  first_name: [Yucheng]
  style: apa
  locale: en
  source: /_bibliography/
  bibliography: papers.bib
  bibliography_template: bib
  replace_strings: true
  join_strings: true
  details_dir: bibliography
  details_link: Details
  query: "@*"
  group_by: year
  group_order: descending

enable_publication_thumbnails: true
enable_publication_badges:
  altmetric: false
  dimensions: false
  google_scholar: true
  inspirehep: false

# -----------------------------------------------------------------------------
# Plugins (保持默认)
# -----------------------------------------------------------------------------
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-scholar
  - jemoji

sass:
  style: compressed

# -----------------------------------------------------------------------------
# Optional UI
# -----------------------------------------------------------------------------
enable_math: true
enable_masonry: true
enable_medium_zoom: true
enable_progressbar: true
enable_tooltips: false
enable_project_categories: true
enable_navbar_social: false
